---

- hosts: all
  become: yes
  roles:
    - base

- hosts: web_servers
  become: yes
  roles:
    - web_servers

- hosts: db_servers
  become: yes
  roles:
    - db_servers

- hosts: file_servers
  become: yes
  roles:
    - file_servers
