---
- name: Update Oracle Linux systems
  hosts: all  # Replace with your inventory group or hostname
  become: true # Required to run package management commands with elevated privileges

  tasks:
    - name: Update all packages on Oracle Linux (using yum for OL7/8 or dnf for OL8+)
      # Use the appropriate module based on your Oracle Linux version
      # For Oracle Linux 7 or 8, use 'yum'
      # For Oracle Linux 8 and newer, 'dnf' is also available and often preferred
      ansible.builtin.yum:
        name: "*"
        state: latest
        update_cache: yes # Ensures package lists are up-to-date
      # If you prefer dnf, replace 'yum' with 'dnf'
      # ansible.builtin.dnf:
      #   name: "*"
      #   state: latest
      #   update_cache: yes

    - name: Check if a reboot is required after kernel update
      ansible.builtin.stat:
        path: /var/run/reboot-required
      register: reboot_required_file

    - name: Reboot if required
      ansible.builtin.reboot:
      when: reboot_required_file.stat.exists
